site_name: Operation
theme:
  name: material
  custom_dir: overrides
  logo: assests/images/operation.png
  favicon: assests/images/operation.png
  features:
    - navigation.instant
extra_css:
  - stylesheets/extra.css
    