name: pybash
secret: underground
type: alpha
command: docker container run --rm -it -v $(pwd):/tmp -v /Users/$USER/.aws/credentials:/root/.aws/credentials -p 5042:5042 -w /tmp operation_pybash
description: Debian shell with Python utils and AWS local credentials (.aws/crendentials). Local data are mapped into the /tmp directory.
