name: pybash
secret: underground
type: alpha
command: docker container run --rm -it -v $(pwd):/tmp -w /tmp operation_pybash
description: Debian shell with Python utils. Local data are mapped into the /tmp directory.