name: ipython
secret: rattlesnake
type: alpha
command: docker container run --rm -it -v $(pwd):/tmp -w /tmp operation_ipython
description: A simple IPython shell. Local data are mapped into the /tmp directory.